### ISSUE TITLE
NPM Package Not Usable

### ISSUE THREAD

**Issue by Joncom** [CocoonIO/cocoon-cloud-sdk#9]
I should note that I can use everything perfectly if I install directly from Git:
```
git clone https://github.com/CocoonIO/cocoon-cloud-sdk.git
cd cocoon-cloud-sdk
npm install
cd out
echo "const cocoonSDK = require('./index.js'); console.log(cocoonSDK);" > main.js
node main.js
```

`node main.js` results in the following output:
```
{ OAuth: [Function: OAuth],
  CocoonAPI: [Function: CocoonAPI],
  ProjectAPI: [Function: ProjectAPI],
  SigningKeyAPI: [Function: SigningKeyAPI],
  UserAPI: [Function: UserAPI],
  Project: [Function: Project],
  SigningKey: [Function: SigningKey],
  User: [Function: User] }
```

OK, so let's start over again, this time using NPM:
```
npm install cocoon-cloud-sdk
echo "const cocoonSDK = require('cocoon-cloud-sdk'); console.log(cocoonSDK);" > main.js
node main.js
```

`node main.js` now results in the following output:
```
module.js:557
    throw err;
    ^

Error: Cannot find module 'cocoon-cloud-sdk'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Library/WebServer/Documents/LTM/stomp/main.js:1:81)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

Curiously, if I inspect the installed NPM package:
```
$ ls node_modules/cocoon-cloud-sdk/
LICENSE		README.md	examples	package.json
```
there does not appear to be anything resembling the "index.js" found in the first example.

**Comment by BlueSialia** [comment]
`npm publish` is executed by Travis on a passed build.

Apparently they changed something since we set the automatic process and that caused a faulty 2.0.2 publish. The version 2.0.3 should be correct now. I'm going to delete the 2.0.2 version.

Thanks for pointing it out.

**Comment by Joncom** [comment]
Yes, it appears to be fixed now.
